package guiProject;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
class Details extends JFrame implements ActionListener {
JPanel p1,p2,p3,p4;
JLabel l1,l2,l3,l4,l5,l6,l7,l8,l9,l10,l11,l12,l13,l14,l15,l16,l17,l18,l19,l20,l21,l22,l23,l24;
static double bal=100000;
static String account,amount,status,status2="---",amount2="000.00",account2="None";
Details(String acc,String amo,String stat,String xy){
  Container con=getContentPane();
  p1=new JPanel();
  p2=new JPanel();
  p3=new JPanel();
  p4=new JPanel();
  p2.setBackground(Color.yellow);
  p3.setBackground(Color.cyan);
  p4.setBackground(Color.orange);
  con.setLayout(new GridLayout(4,1));
  con.add(p1);
  con.add(p2);
  con.add(p3);
  con.add(p4);
  p1.setBorder(BorderFactory.createLineBorder(Color.black));
  p2.setBorder(BorderFactory.createDashedBorder(Color.black));
  p3.setBorder(BorderFactory.createLineBorder(Color.black));
  p4.setBorder(BorderFactory.createLineBorder(Color.black));
  setTitle("Account Details");
  l9=new JLabel("Account Details");
  p1.add(l9);
  setVisible(true);
  setSize(500,600);
  p2.setLayout(new GridLayout(5,2));
  l1=new JLabel("Name:");
  l2=new JLabel("Aditya");
  l3=new JLabel("Phone Number:");
  l4=new JLabel("7989327096");
  l5=new JLabel("Account Number:");
  l6=new JLabel("2100xxx268");
  l7=new JLabel("Pan Card Number:");
  l8=new JLabel("78xxxx528");
  p2.add(l1);
  p2.add(l2);
  p2.add(l3);
  p2.add(l4);
  p2.add(l5);
  p2.add(l6);
  p2.add(l7);
  p2.add(l8);
  double am=Double.parseDouble(amo);
    bal=bal-am;
    String balance=Double.toString(bal);
  l23=new JLabel("Balance:");
  l24=new JLabel(balance);
  p2.add(l23);
  p2.add(l24);
  l10=new JLabel("Transaction Details");
  p3.add(l10);
  p4.setLayout(new GridLayout(3,3));
  l11=new JLabel("1");
  l12=new JLabel(acc);
  account=acc;
  l13=new JLabel(stat);
  status=stat;
  l14=new JLabel(amo);
  amount=amo;
  l15=new JLabel("2");
  l16=new JLabel(account2);
  l17=new JLabel(status2);
  l18=new JLabel(amount2);
  l19=new JLabel("S.No");
  l20=new JLabel("Bank account");
  l21=new JLabel("Status");
  l22=new JLabel("Amount");
  p4.add(l19);
  p4.add(l20);
  p4.add(l21);
  p4.add(l22);
  p4.add(l11);
  p4.add(l12);
  p4.add(l13);
  p4.add(l14);
  p4.add(l15);
  p4.add(l16);
  p4.add(l17);
  p4.add(l18);
}
Details(String acc,String amo,String statu){
  Container con=getContentPane();
  p1=new JPanel();  
  p2=new JPanel();
  p3=new JPanel();
  p4=new JPanel();
  p2.setBackground(Color.yellow);
  p3.setBackground(Color.cyan);
  p4.setBackground(Color.orange);
  con.setLayout(new GridLayout(4,1));
  con.add(p1);
  con.add(p2);
  con.add(p3);
  con.add(p4);
  p1.setBorder(BorderFactory.createLineBorder(Color.black));
  p2.setBorder(BorderFactory.createDashedBorder(Color.black));
  p3.setBorder(BorderFactory.createLineBorder(Color.black));
  p4.setBorder(BorderFactory.createLineBorder(Color.black));
  setTitle("Account Details");
  l9=new JLabel("Account Details");
  p1.add(l9);
  setVisible(true);
  setSize(500,600);
  p2.setLayout(new GridLayout(5,2));
  l1=new JLabel("Name:");
  l2=new JLabel("Aditya");
  l3=new JLabel("Phone Number:");
  l4=new JLabel("9290793922");
  l5=new JLabel("Account Number:");
  l6=new JLabel("2100xxx268");
  l7=new JLabel("Pan Card Number:");
  l8=new JLabel("78xxxx528");
  p2.add(l1);
  p2.add(l2);
  p2.add(l3);
  p2.add(l4);
  p2.add(l5);
  p2.add(l6);
  p2.add(l7);
  p2.add(l8);
  l23=new JLabel("Balance:");
  double am=Double.parseDouble(amo);
  bal=bal+am;
    String balance=Double.toString(bal);
  l24=new JLabel(balance);
  p2.add(l23);
  p2.add(l24);
  l10=new JLabel("Transaction Details");
  p3.add(l10);
  p4.setLayout(new GridLayout(3,3));
  l11=new JLabel("1");
  l12=new JLabel(account);
  l13=new JLabel(status);
  l14=new JLabel(amount);
  l15=new JLabel("2");
  l16=new JLabel(acc);
  l17=new JLabel(statu);
  status2=statu;
  l18=new JLabel(amo);
  amount2=amo;
  l19=new JLabel("S.No");
  l20=new JLabel("Bank account");
  l21=new JLabel("Status");
  l22=new JLabel("Amount");
  p4.add(l19);
  p4.add(l20);
  p4.add(l21);
  p4.add(l22);
  p4.add(l11);
  p4.add(l12);
  p4.add(l13);
  p4.add(l14);
  p4.add(l15);
  p4.add(l16);
  p4.add(l17);
  p4.add(l18);
}
  public void actionPerformed(ActionEvent e) {

  }

}
